project:
  type: book

book:
  title: "Data Engineering"
  author: "Sam Mak"
  sidebar: 
    background: "black"
    search: false
  chapters:
    - index.qmd
    - intro.qmd
    - s4.qmd
    - odbc.qmd
    - r_and_dbms.qmd
    - references.qmd

bibliography: references.bib
csl: csl.csl

format:
  html:
    theme: darkly
    backgroundcolor: "black"
    date-modified: last-modified
    toc: false
    fontcolor: "#AAAAAA"
    css: quarto_books_style_1.css
    number-sections: false
    section-divs: true
    monobackgroundcolor: "#303030"
    code-overflow: wrap
  
    grid: 
      body-width: 1100px
      margin-width: 100px
      sidebar-width: 180px
      
  pdf:
    documentclass: scrreprt
    

editor: source

